name: Curation (Define notebook, code, data locks)

# -- This workflow ingests notebook, code, and data requirements from the
# -- notebook repositories and computes new constraint resolutions and git
# -- hashes and/or symbolic references.  The completed spec is pushed to GHCR
# -- in a degenerate nbs_* image that only contains metadata.  nbw is able to
# -- download and extract the metadata using Docker and the --docker-xxx
# -- commands which glob on spec names.

on:
  workflow_dispatch:
    inputs:
      spec_file:
        description: 'The path to the wrangler spec file in the notebook repo'
        required: false
        type: string
        default: 'specs/roman/nbw-wrangler-spec.yaml'
      wrangler_owner:
        description: 'The owner of the GitHub nb-wrangler repo to use for the tool'
        required: false
        type: string
        default: spacetelescope
      wrangler_ref:
        description: 'The branch/tag/ref of nb-wrangler to use for the tool'
        required: false
        type: string
        default: 'main'
  workflow_call:
    inputs:
      spec_file:
        description: 'The path to the wrangler spec file in the notebook repo'
        required: false
        type: string
        default: 'specs/roman/nbw-wrangler-spec.yaml'
      wrangler_owner:
        description: 'The owner of the GitHub nb-wrangler repo to use for the tool'
        required: false
        type: string
        default: spacetelescope
      wrangler_ref:
        description: 'The branch/tag/ref of nb-wrangler to use for the tool'
        required: false
        type: string
        default: 'main'

defaults:
  run:
    shell: bash

jobs:
  nb-wrangler-curate:
    name: Curate (Define notebooks, code, data)
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
      packages: write       # Allows GITHUB_TOKEN to push to GHCR
    steps:
      - name: Checkout "Notebook Repo"
        uses: actions/checkout@v4

      - name: Set up system tools
        run: |
          git config --global user.email "homer@stsci.edu"
          git config --global user.name "Homer S."

      - name: Configure wrangler spec location, overrides mode, and repos directory
        run: |
          # Primary spec workflow input
          export NBW_SPEC=$GITHUB_WORKSPACE/${{ inputs.spec_file }}
          echo NBW_SPEC=$NBW_SPEC >>$GITHUB_ENV

          # name inside Dockerfile
          echo SPEC_NAME=nbw-wrangler-spec.yaml >>$GITHUB_ENV

          # Define where repo clones should be checked out
          export NBW_REPOS_DIR="/tmp/references"
          echo NBW_REPOS_DIR=$NBW_REPOS_DIR >>$GITHUB_ENV

          # Lock the spec requirements to dev mode (if available) during curation and
          # use dev_overrides:
          export NBW_OVERRIDES_MODE="--dev"
          echo NBW_OVERRIDES_MODE="--dev" >>$GITHUB_ENV

      - name: Checkout and configure wrangler for source repo (can be overridden for --dev)
        run: |
          # Use the bootstrap script from master repo to resolve the target repo; used for bootstrap only
          curl https://raw.githubusercontent.com/${{ inputs.wrangler_owner }}/nb-wrangler/refs/heads/main/nb-wrangler  >nb-wrangler
          chmod +x nb-wrangler

          # Identify the real repo and reference (branch,tag,hash) determining wrangler used for build
          export WRANGLER_URL=https://github.com/${{ inputs.wrangler_owner }}/nb-wrangler.git
          ANS=$(./nb-wrangler resolve-ref ${NBW_SPEC} ${{ inputs.wrangler_ref }})
          export WRANGLER_REF="${ANS}"
          echo WRANGLER_URL=$WRANGLER_URL >> $GITHUB_ENV
          echo WRANGLER_REF=$WRANGLER_REF >> $GITHUB_ENV

          # Clone and configure exact wrangler source code,  nominally a prod copy or a (personal?) dev copy
          cd ${GITHUB_WORKSPACE}/..
          git clone ${WRANGLER_URL} nb-wrangler-tool
          cd nb-wrangler-tool
          git checkout ${WRANGLER_REF}

      - name: Bootstrap Wrangler
        run: |
          # Given the exact version of wrangler source code,  run the full bootstrap to set up a wrangler environment
          cd $GITHUB_WORKSPACE/../nb-wrangler-tool
          ./nb-wrangler bootstrap
          source ./nb-wrangler environment
          micromamba install --yes syft grype

      - name: Validate Wrangler spec for image / environment
        run: |
          cd $GITHUB_WORKSPACE/../nb-wrangler-tool
          source ./nb-wrangler environment
          ./nb-wrangler $NBW_SPEC --spec-validate

      - name: Set up workflow env vars
        run: |
          # Both of owner/repo, e.g. spacetelescope/roman_notebooks
          export IMAGE_REPO=$GITHUB_REPOSITORY
          echo IMAGE_REPO=$IMAGE_REPO >>$GITHUB_ENV
          export IMAGE_ROOT=ghcr.io/$IMAGE_REPO
          echo IMAGE_ROOT=$IMAGE_ROOT >> $GITHUB_ENV

          # Full repo path of degenerate spec-only image, including tag
          ANS=$(./nb-wrangler --spec-name 2>/dev/null )_$GITHUB_RUN_NUMBER
          export SPEC_TAG="${ANS}"
          echo SPEC_TAG=$SPEC_TAG >> $GITHUB_ENV
          echo SPEC_IMAGE_ID=${IMAGE_ROOT}:${SPEC_TAG} >> $GITHUB_ENV

          # Full repo path of executable image, including tag
          ANS=$(./nb-wrangler --spi-image-name 2>/dev/null )_$GITHUB_RUN_NUMBER
          export IMAGE_TAG="${ANS}"
          echo IMAGE_TAG=$IMAGE_TAG  >> $GITHUB_ENV
          echo IMAGE_ID=${IMAGE_ROOT}:${IMAGE_TAG} >> $GITHUB_ENV

          # Nominally which classic mission (roman, tike, jwebbinar) or "wrangler" for generic builds
          # Note that generic builds have very little or no Docker-level customization, such as extra C programs
          # built under Docker using make.  Classic deployments
          ANS=$(yq -r .image_spec_header.deployment_name ${NBW_SPEC})
          export SPEC_DEPLOYMENT="${ANS}"
          echo  SPEC_DEPLOYMENT=$SPEC_DEPLOYMENT >> $GITHUB_ENV

          # Root location for curated data and environment archives, also needed for notebook tests
          source ./nb-wrangler environment
          echo NBW_PANTRY=$NBW_PANTRY >>$GITHUB_ENV

      - name: Curate Environment
        run: |
            cd $GITHUB_WORKSPACE/../nb-wrangler-tool
            ./nb-wrangler --spec-reset
            ./nb-wrangler --curate

      - name: Curate Data
        run: |
            cd $GITHUB_WORKSPACE/../nb-wrangler-tool
            ./nb-wrangler --data-reset-curation
            ./nb-wrangler --data-curate

      - name: Log in to GHCR
        run: |
          echo "${{ github.token }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Generate Dockerfile for spec
        run: |
          cd $GITHUB_WORKSPACE/../nb-wrangler-tool
          mkdir docker-root
          cd docker-root
          cp ${NBW_SPEC} .
          cat > Dockerfile << EOF
          FROM scratch
          COPY $(basename ${NBW_SPEC}) ${SPEC_NAME}
          EOF

      - name: Build Spec archive and push to GHCR
        run: |
          cd $GITHUB_WORKSPACE/../nb-wrangler-tool/docker-root
          docker build -t ${SPEC_IMAGE_ID} -f Dockerfile .
          docker push ${SPEC_IMAGE_ID}

      - name: Build Image and Push to GHCR
        run: |
          set -x
          cd $GITHUB_WORKSPACE/../nb-wrangler-tool
          ./nb-wrangler --clone-repos --spi-inject-reqs --spi-image-build ${NBW_OVERRIDES_MODE}
          docker image ls
          docker tag notebook-${SPEC_DEPLOYMENT}:latest   ${IMAGE_ID}
          docker push ${IMAGE_ID}
          rm -rf $REPOS_DIR

      - name: Test imports for native environment (adivsory)
        run: |
            cd $GITHUB_WORKSPACE/../nb-wrangler-tool
            ./nb-wrangler --test-imports --test-copy-shared ../../shared ${NBW_OVERRIDES_MODE}

      - name: Test notebooks inside image (advisory)
        run: |
          cd $REPOS_DIR/science-platform-images
          scripts/image-configure ${SPEC_DEPLOYMENT}
          source setup-env
          mkdir ${HOME}/crds_cache
          # make dirs globally writable since uid/gid inside Docker may not match outside
          chmod -R 777 ${HOME}/crds_cache
          chmod -R 777 ${NBW_PANTRY}
          image-test --test-notebooks ${NBW_OVERRIDES_MODE}

      - name: Scan Image (advisory)
        run: |
          cd $GITHUB_WORKSPACE/../nb-wrangler-tool
          ./nb-wrangler --clone-repos ${NBW_OVERRIDES_MODE}
          cd $REPOS_DIR/science-platform-images
          scripts/image-configure ${SPEC_DEPLOYMENT}
          source setup-env
          scripts/image-scan
