name: Re-tag Existing Image

on:
  workflow_dispatch:
    inputs:
      input_tag:
        description: The GHCR image tag of an existing image
        required: true
        type: string
      output_tag:
        description: The GHCR alias tag being created for the input image
        required: true
        type: string

  workflow_call:
    inputs:
      input_tag:
        description: The GHCR image tag of an existing image
        required: true
        type: string
      output_tag:
        description: The GHCR image tag alias for the input image
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:
  nb-wrangler-retag:
    name: Re-tag/Alias Existing Image
    runs-on: 'ubuntu-24.04'
    permissions:
      contents: read
      packages: write       # Allows GITHUB_TOKEN to push to GHCR
    steps:
      # ----- - name: Set up Python
      # -----   uses: actions/setup-python@v6
      # -----   with:
      # -----     python-version: "3.12"
      # -----     cache: pip

      # ----- - name: Update pip
      # -----   run: |
      # -----     python -m pip install --upgrade pip

      # ----- - name: Pip install nb-wrangler
      # -----   run: |
      # -----     pip install nb-wrangler

      - name: Verify Docker availability
        run: docker version

      - name: Set up system tools
        run: |
          git config --global user.email "homer@stsci.edu"
          git config --global user.name "Homer S."

      - name: Set up workflow env vars
        run: |
          # Force --prod mode for wrangler
          export NBW_OVERRIDES_MODE="--prod"
          echo NBW_OVERRIDES_MODE=${NBW_OVERRIDES_MODE} >> $GITHUB_ENV

          export IMAGE_ROOT="ghcr.io/spacetelescope/nb-wrangler-images"
          echo 'IMAGE_ROOT="ghcr.io/spacetelescope/nb-wrangler-images"' >> $GITHUB_ENV

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}  # or PAT with write:packages

      - name: Pull source image
        run: |
          docker pull ${IMAGE_ROOT}:${{ inputs.input_tag }}

      - name: Add new tag and push
        run: |
             docker tag  ${IMAGE_ROOT}:${{ inputs.input_tag }}  ${IMAGE_ROOT}:${{ inputs.output_tag }}
             docker push ${IMAGE_ROOT}:${{ inputs.output_tag }}
